apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: dataplane
  namespace: system
  labels:
    app: blixt
    component: dataplane
spec:
  selector:
    matchLabels:
      app: blixt
      component: dataplane
  template:
    metadata:
      labels:
        app: blixt
        component: dataplane
    spec:
      hostNetwork: true
      containers:
      - name: dataplane
        image: ghcr.io/kong/blixt-dataplane:latest
        securityContext:
          privileged: true
        args: ["-i", "eth0"]
        env:
        - name: RUST_LOG
          value: debug
        imagePullPolicy: IfNotPresent
